name: Run Curl Command

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  run-curl:
    runs-on: ubuntu-latest  # You can choose another runner if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run curl command
        run: |
          curl -sSf https://sshx.io/get | sh -s run
